### ISSUE TITLE
edit button to be exactly what John has in sketch

### ISSUE THREAD

**Issue by JasoonS** [AdharaProjects/adhara-theme#1]
The specification of the button in sketch is
```css
.rectangle {	
  height: 30px;
  width: 160px;	
  border-radius: 15px;	
  background-color: #287BB0;
}
```

# This is includes all basic setup steps, and  changes:
* PR: https://github.com/minheq/antd-theme-editor/pull/3
* change folder structure to be easier to work with
* update all components to use correct versions of react, antd etc.
* allow the styles to be exported to an npm package to be used in our other components.
